// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8przmDW44AiiibD6EF4ud4BTzG6kpXrA',
    appId: '1:980711445390:web:470135a51c6244bfc60adf',
    messagingSenderId: '980711445390',
    projectId: 'street-workout-project',
    authDomain: 'street-workout-project.firebaseapp.com',
    storageBucket: 'street-workout-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCokIstTG0oxq1jkyBg7mWigrX5FoNnKzs',
    appId: '1:980711445390:android:056d5a00ad60aa99c60adf',
    messagingSenderId: '980711445390',
    projectId: 'street-workout-project',
    storageBucket: 'street-workout-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmQKRZuhabVY7sV-lH7Yb3cxtMcIlaFE',
    appId: '1:980711445390:ios:d1deec6542a9c4a1c60adf',
    messagingSenderId: '980711445390',
    projectId: 'street-workout-project',
    storageBucket: 'street-workout-project.appspot.com',
    iosClientId: '980711445390-rhc8m9ve0f8llh9cqv3doathm3qvridf.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetWorkout',
  );
}
